theme: jekyll-theme-minimal
title: 
<div class="text-purple">
  Jennie Chung
</div>
email: jjchung [at] caltech [dot] edu
linkedin: https://www.linkedin.com/in/jech/
description:  CS+Math Major at California Institute of Technology '22
